// <auto-generated />
using System;
using BethanysPieShopHRM.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BethanysPieShopHRM.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240905092618_addDownload")]
    partial class addDownload
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClassLibraryEmotes.Emote", b =>
                {
                    b.Property<int>("EmoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmoteId"), 1L, 1);

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(59)
                        .HasColumnType("nvarchar(59)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumDownload")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Version")
                        .HasColumnType("float");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("EmoteId");

                    b.HasIndex("UserId");

                    b.ToTable("Emotes");

                    b.HasData(
                        new
                        {
                            EmoteId = 1,
                            Approved = true,
                            CreationDate = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "the poor coballa this one regrets what he has done",
                            Height = 128,
                            Name = "oh",
                            NumDownload = 0,
                            Status = 0,
                            UserId = 1,
                            Version = 1.0,
                            Weight = "160KB",
                            Width = 128
                        },
                        new
                        {
                            EmoteId = 2,
                            Approved = true,
                            CreationDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "this freak cat laughs at you resoundingly",
                            Height = 96,
                            Name = "LMAO",
                            NumDownload = 0,
                            Status = 1,
                            UserId = 2,
                            Version = 1.2,
                            Weight = "29KB",
                            Width = 384
                        });
                });

            modelBuilder.Entity("ClassLibraryEmotes.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserName = "JuanitoXD3234542"
                        },
                        new
                        {
                            UserId = 2,
                            UserName = "Jorge353424234"
                        },
                        new
                        {
                            UserId = 3,
                            UserName = "Abascalterrorista"
                        },
                        new
                        {
                            UserId = 4,
                            UserName = "gato_vietnamita"
                        },
                        new
                        {
                            UserId = 5,
                            UserName = "jose:D"
                        },
                        new
                        {
                            UserId = 6,
                            UserName = "chinchon"
                        },
                        new
                        {
                            UserId = 7,
                            UserName = "bobooklk"
                        },
                        new
                        {
                            UserId = 8,
                            UserName = "miguelin_de_murcia"
                        },
                        new
                        {
                            UserId = 9,
                            UserName = "nayara_rivas_who"
                        });
                });

            modelBuilder.Entity("ClassLibraryEmotes.Emote", b =>
                {
                    b.HasOne("ClassLibraryEmotes.User", "User")
                        .WithMany("OwnEmote")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibraryEmotes.User", b =>
                {
                    b.Navigation("OwnEmote");
                });
#pragma warning restore 612, 618
        }
    }
}
